In [1]:
# NumPy Basics - Learning Notebook
import numpy as np

# 1. Create a basic list and convert to NumPy array
arr = [10, 20, 30]
narr = np.array(arr)
print(narr)  # Output: [10 20 30]

# 2. Check array type and dimension
print(type(narr))     # <class 'numpy.ndarray'>
print(narr.ndim)      # 1 (1D array)

# 3. Create a 2D array
arr = [[10, 20, 30], [40, 50, 60], [70, 40, 58]]
narr = np.array(arr)
print(type(narr))     # <class 'numpy.ndarray'>
print(narr.ndim)      # 2
print(narr.shape)     # (3, 3)

# 4. Reshape a 1D array into 2D (2 rows, 5 columns)
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped = array.reshape(2, 5)
print(reshaped)

# 5. Basic statistics
print(array.min(), array.max(), array.sum())  # 0 9 45

# 6. Flattening a 2D array
array = np.array([[10, 20], [30, 40], [50, 60]])
flat_array = array.flatten()
print(flat_array)  # [10 20 30 40 50 60]

# 7. Convert NumPy array to list
lst = array.tolist()
print(lst)          # [[10, 20], [30, 40], [50, 60]]
print(type(lst))    # <class 'list'>

# 8. Create zero matrix
z = np.zeros((3, 3))
print(z)

# 9. Create one matrix
o = np.ones((3, 4))
print(o)

# 10. Identity matrix
e = np.eye(6)
print(e)

# 11. Generate array with arange
array = np.arange(0, 20)
print(array)

# 12. Reshape into 3D array
narray = array.reshape(1, 5, 4)
print(narray.ndim)  # 3
print(narray)

# 13. Standard deviation and variance
print(narray.std())  # Standard deviation
print(narray.var())  # Variance


[10 20 30]
<class 'numpy.ndarray'>
1
<class 'numpy.ndarray'>
2
(3, 3)
[[0 1 2 3 4]
 [5 6 7 8 9]]
0 9 45
[10 20 30 40 50 60]
[[10, 20], [30, 40], [50, 60]]
<class 'list'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
3
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]]
5.766281297335398
33.25


In [8]:
# create two dimensional array having 6 rows and 5 coloumns

array = np.array(np.arange(1,31))
two_array = array.reshape(6,5)


In [7]:
two_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
#slicing numpy array 2 se start hoga 3 pe khatam coloum mai start hoga 1 se 4 pe khatam 
two_array[5:,-2:][0][0]

29

In [ ]:
two_array[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])